<html>
<head>
    <title>Agenda - TreinaWeb Cursos - PHP Intermediário</title>
    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="<?=assets()->css('bootstrap.min.css');?>">
    <link rel="stylesheet" href="<?=assets()->css('main.css');?>">
    <script type="text/javascript" src="<?=assets()->js('jquery.min.js');?>"></script>
</head>
<body>
<div class="container">